DROP DATABASE medly_db;
CREATE DATABASE medly_db;

use medly_db;

INSERT INTO medly_db.roles (role) VALUES ('ROLE_ADMIN');
INSERT INTO medly_db.roles (role) VALUES ('ROLE_DOCTOR');
INSERT INTO medly_db.roles (role) VALUES ('ROLE_PATIENT');


INSERT INTO users(id, first_name, last_name, username, email, password, enabled, role_id)
VALUES(1, 'joe', 'joe', 'test', 'test@test.com', '$2a$10$O5lrKNXfAdWWpf0P3Ij7Du03J7WuCRRtVDT7JGJwHTighGmweFhDO', 1, 3),
      (2, 'tom', 'tom', 'root', 'tester@test.com', '$2a$12$P4EO3NigCVDe5QD5YEDx4Og4p80VrLu8ka4Hp.qc97YcsNVIjkytq', 1, 3);

INSERT INTO medly_db.medications (brand_name, generic_name)
    VALUES ('Albuterol', 'ProAir® HFA'),
      ('Alendronate', 'Fosamax®'),
      ('Allopurinol', 'Zyloprim®'),
      ('Alprazolam', 'Xanax®'),
      ('Amitriptyline', 'Elavil®'),
      ('Amlodipine', 'Norvasc®'),
      ('Amoxicillin', 'Amoxil®'),
      ('Aripiprazole', 'Abilify®'),
      ('Atenolol', 'Tenormin®'),
      ('Atorvastatin', 'Lipitor®'),
      ('Azithromycin', 'Zithromax®'),
      ('Benazepril', 'Lotensin®'),
      ('Budesonide + Formoterol', 'Symbicort®'),
      ('Buprenorphine + Naloxone', 'Suboxone®'),
      ('Carisoprodol', 'Soma®'),
      ('Carvedilol', 'Coreg®'),
      ('Celecoxib', 'Celebrex®'),
      ('Cephalexin', 'Keflex®'),
      ('Ciprofloxacin', 'Cipro®'),
      ('Citalopram', 'Celexa®'),
      ('Clonazepam', 'Klonopin®'),
      ('Clonidine', 'Catapres®'),
      ('Clopidogrel', 'Plavix®'),
      ('Codeine / APAP', 'Tylenol® #2'),
      ('Cyclobenzaprine', 'Flexeril®'),
      ('Dexlansoprazole', 'Dexilant®'),
      ('Diazepam', 'Valium®'),
      ('Digoxin', 'Lanoxin®'),
      ('Diltiazem', 'Cardizem®'),
      ('Duloxetine', 'Cymbalta®'),
      ('Enalapril', 'Vasotec®'),
      ('Escitalopram', 'Lexapro®'),
      ('Esomeprazole', 'Nexium®'),
      ('Estrogen', 'Premarin®'),
      ('Ezetimibe', 'Zetia®'),
      ('Famotidine', 'Pepcid®'),
      ('Fluconazole', 'Diflucan®'),
      ('Fluoxetine', 'Prozac®'),
      ('Fluticasone', 'Flonase®'),
      ('Fluticasone + Salmeterol', 'Advair®'),
      ('Folic Acid', 'Folvite®'),
      ('Furosemide', 'Lasix®'),
      ('Gabapentin', 'Neurontin®'),
      ('Glyburide', 'Diabeta®'),
      ('Hydrochlorothiazide', 'HCTZ'),
      ('Hydrocodone/APAP', 'Vicodin®'),
      ('Ibuprofen', 'Advil®'),
      ('Insulin Aspart', 'Novolog®'),
      ('Insulin Detemir', 'Levemir®'),
      ('Insulin Glargine', 'Lantus®'),
      ('Latanoprost', 'Xalatan®'),
      ('Levofloxacin', 'Levaquin®'),
      ('Levothyroxine', 'Synthroid®'),
      ('Lisdexamfetamine', 'Vyvanse®'),
      ('Lisinopril', 'Prinivil®'),
      ('Lisinopril + HCTZ', 'Prinizide®'),
      ('Loratadine', 'Claritin®'),
      ('Lorazepam', 'Ativan®'),
      ('Losartan + HCTZ', 'Hyzaar®'),
      ('Lovastatin', 'Mevacor®'),
      ('Meloxicam', 'Mobic®'),
      ('Memantine', 'Namenda®'),
      ('Metformin', 'Glucophage®'),
      ('Methylphenidate', 'Concerta®'),
      ('Methylprednisolone', 'Medrol®'),
      ('Metoprolol', 'Lopressor®'),
      ('Mometasone', 'Nasonex®'),
      ('Montelukast', 'Singulair®'),
      ('Olanzapine', 'Zyprexa®'),
      ('Omeprazole', 'Prilosec®'),
      ('Oxycodone', 'OxyContin®'),
      ('Oxycodone/APAP', 'Percocet®'),
      ('Pantoprazole', 'Protonix®'),
      ('Paroxetine', 'Paxil®'),
      ('Penicillin', 'Pen VK®'),
      ('Pioglitazone', 'Actos®'),
      ('Potassium', 'K-Tab®'),
      ('Pravastatin', 'Pravachol®'),
      ('Prednisolone', 'Omnipred®'),
      ('Prednisone', 'Deltasone®'),
      ('Pregabalin', 'Lyrica®'),
      ('Promethazine', 'Phenergan®'),
      ('Quetiapine', 'Seroquel®'),
      ('Ranitidine', 'Zantac®'),
      ('Risedronate', 'Actonel®'),
      ('Rivaroxaban', 'Xarelto®'),
      ('Rosuvastatin', 'Crestor®'),
      ('Sertraline', 'Zoloft®'),
      ('Simvastatin', 'Zocor®'),
      ('Sitagliptin', 'Januvia®'),
      ('Tamsulosin', 'Flomax®'),
      ('Tiotropium', 'Spiriva®'),
      ('Tolterodine', 'Detrol®'),
      ('Tramadol', 'Ultram®'),
      ('Trazodone', 'Desyrel®'),
      ('Triamterene + HCTZ', 'Dyazide®'),
      ('Valsartan', 'Diovan®'),
      ('Venlafaxine', 'Effexor®'),
      ('Warfarin', 'Coumadin®'),
      ('Zolpidem', 'Ambien®');